// Mocks generated by Mockito 5.0.7 from annotations
// in flutter_catalog/test/data/repo/BikeRepositoryImpl_test.dart.
// Do not manually edit this file.

import 'package:flutter_catalog/data/repo/BikeRepositoryImpl.dart' as _i3;
import 'package:flutter_catalog/network/api/DummyCatalogAPIImpl.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [CatalogAPIImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogAPIImpl extends _i1.Mock implements _i2.DummyCatalogAPIImpl {
  MockCatalogAPIImpl() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [BikeRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockBikeRepositoryImpl extends _i1.Mock
    implements _i3.BikeRepositoryImpl {
  MockBikeRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }
}
